require 'fileutils'
require 'open3'
require 'tmpdir'

class BroadcastMasterRenderer
  RenderError = Class.new(StandardError)
  TARGET_LOUDNESS = ENV.fetch('BROADCAST_TARGET_LUFS', '-16')
  TRUE_PEAK = ENV.fetch('BROADCAST_TRUE_PEAK_DB', '-1.5')
  LOUDNESS_RANGE = ENV.fetch('BROADCAST_LOUDNESS_RANGE', '11')
  OUTPUT_SAMPLE_RATE = '48000'
  OUTPUT_BITRATE = '192k'
  SOURCE_APP_COMMENT = 'Generated by Human Frequency'

  def initialize(playlist, s3_service: nil, downloader: nil, command_runner: Open3)
    @playlist = playlist
    @s3_service = s3_service || AwsS3Service.new(ENV.fetch('AWS_BUCKET_NAME', 'radio-denver'))
    @downloader = downloader || AudioSourceDownloader.new(s3_service: @s3_service)
    @command_runner = command_runner
    @render_report = base_render_report
  end

  def render
    sources = render_sources
    raise RenderError, 'Add playable audio before rendering a broadcast master.' if sources.empty?

    playlist.update!(render_status: 'rendering', render_error: nil)

    Dir.mktmpdir("human-frequency-show-#{playlist.id}-") do |directory|
      normalized_paths = normalize_sources(sources, directory).map { |item| item.fetch(:path) }
      master_path = File.join(directory, master_filename)
      concatenate(normalized_paths, master_path, directory)
      persist_master(master_path)
    end
  rescue RenderError => error
    record_failed_report(error.message)
    playlist.update_columns(render_status: 'failed', render_error: error.message, rendered_at: nil)
    raise
  rescue StandardError => error
    record_failed_report('Broadcast master rendering failed.')
    playlist.update_columns(render_status: 'failed', render_error: 'Broadcast master rendering failed.', rendered_at: nil)
    Rails.logger.error("Broadcast master render failed for playlist #{playlist.id}: #{error.class}: #{error.message}")
    raise RenderError, 'Broadcast master rendering failed.'
  end

  private

  attr_reader :playlist, :s3_service, :downloader, :command_runner

  def render_sources
    if playlist.full_show_audio_file.present?
      return [audio_file_source(playlist.full_show_audio_file, playlist.name)]
    end

    playlist.songs.includes(:audio_file).map do |song|
      if song.audio_file.present?
        audio_file_source(song.audio_file, song.name)
      elsif song.file_url.present?
        { title: song.name, url: song.file_url, extension: File.extname(song.file_name.to_s).presence || '.audio' }
      end
    end.compact
  end

  def audio_file_source(audio_file, title)
    {
      title: title,
      s3_key: audio_file.s3_key,
      url: audio_file.url,
      extension: File.extname(audio_file.name.to_s).presence || '.audio'
    }
  end

  def normalize_sources(sources, directory)
    sources.each_with_index.map do |source, index|
      input_path = File.join(directory, format('source-%03d%s', index + 1, source[:extension]))
      output_path = File.join(directory, format('normalized-%03d.wav', index + 1))
      downloader.download(source, input_path)
      measurement = measure_loudness(input_path, source, index)
      run_ffmpeg(
        '-i', input_path,
        '-vn',
        '-af', loudnorm_filter(measurement),
        '-ar', OUTPUT_SAMPLE_RATE,
        '-ac', '2',
        '-c:a', 'pcm_s16le',
        output_path
      )
      record_source_report(source, input_path, output_path, measurement)
      { path: output_path, measurement: measurement }
    end
  end

  def concatenate(normalized_paths, output_path, directory)
    concat_path = File.join(directory, 'concat.txt')
    File.write(concat_path, normalized_paths.map { |path| "file '#{path}'" }.join("\n"))

    run_ffmpeg(
      '-f', 'concat',
      '-safe', '0',
      '-i', concat_path,
      '-vn',
      '-c:a', 'libmp3lame',
      '-b:a', OUTPUT_BITRATE,
      '-ar', OUTPUT_SAMPLE_RATE,
      '-ac', '2',
      '-metadata', "title=#{playlist.name}",
      '-metadata', "artist=#{playlist.host_name}",
      '-metadata', "album=#{playlist.name}",
      '-metadata', "date=#{Time.current.year}",
      '-metadata', "comment=#{master_comment}",
      output_path
    )
  end

  def run_ffmpeg(*arguments)
    _stdout, stderr, status = command_runner.capture3('ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', *arguments)
    return if status.success?

    message = stderr.to_s.lines.last(3).join(' ').strip
    raise RenderError, "FFmpeg could not process the show audio. #{message}".strip
  rescue Errno::ENOENT
    raise RenderError, 'FFmpeg is not installed on the rendering server.'
  end

  def run_ffmpeg_capture(*arguments, loglevel: 'error')
    stdout, stderr, status = command_runner.capture3('ffmpeg', '-hide_banner', '-nostats', '-loglevel', loglevel, '-y', *arguments)
    return { stdout: stdout.to_s, stderr: stderr.to_s, status: status } if status.success?

    message = stderr.to_s.lines.last(3).join(' ').strip
    raise RenderError, "FFmpeg could not process the show audio. #{message}".strip
  rescue Errno::ENOENT
    raise RenderError, 'FFmpeg is not installed on the rendering server.'
  end

  def measure_loudness(input_path, source, index)
    result = run_ffmpeg_capture(
      '-i', input_path,
      '-af', one_pass_loudnorm_filter(print_format: true),
      '-f', 'null',
      '-',
      loglevel: 'info'
    )
    measurements = parse_loudnorm_json(result[:stdout], result[:stderr])
    warn_for_true_peak(source, index, measurements)
    measurements
  rescue RenderError => error
    render_report[:ffmpeg_errors] << {
      input_file: File.basename(input_path),
      title: source[:title],
      message: error.message
    }
    raise
  end

  def parse_loudnorm_json(*streams)
    text = streams.compact.join("\n")
    match = text.match(/\{\s*"input_i".*?\}/m)
    return nil unless match

    JSON.parse(match[0])
  rescue JSON::ParserError
    nil
  end

  def loudnorm_filter(measurement)
    return one_pass_loudnorm_filter unless measurement_present?(measurement)

    [
      "loudnorm=I=#{TARGET_LOUDNESS}",
      "TP=#{TRUE_PEAK}",
      "LRA=#{LOUDNESS_RANGE}",
      "measured_I=#{measurement['input_i']}",
      "measured_TP=#{measurement['input_tp']}",
      "measured_LRA=#{measurement['input_lra']}",
      "measured_thresh=#{measurement['input_thresh']}",
      "offset=#{measurement['target_offset']}",
      'linear=true',
      'print_format=json'
    ].join(':')
  end

  def one_pass_loudnorm_filter(print_format: false)
    filter = "loudnorm=I=#{TARGET_LOUDNESS}:TP=#{TRUE_PEAK}:LRA=#{LOUDNESS_RANGE}"
    print_format ? "#{filter}:print_format=json" : filter
  end

  def measurement_present?(measurement)
    measurement.is_a?(Hash) &&
      %w[input_i input_tp input_lra input_thresh target_offset].all? { |key| measurement[key].present? }
  end

  def warn_for_true_peak(source, index, measurement)
    true_peak = measurement&.dig('input_tp').to_f
    return unless measurement&.dig('input_tp').present? && true_peak > TRUE_PEAK.to_f

    render_report[:clipping_warnings] << {
      source_index: index + 1,
      title: source[:title],
      true_peak: measurement['input_tp'],
      target_true_peak: TRUE_PEAK,
      message: 'Measured true peak is above the broadcast target.'
    }
  end

  def record_source_report(source, input_path, output_path, measurement)
    render_report[:normalization_mode] = measurement_present?(measurement) ? 'two-pass' : 'one-pass'
    render_report[:input_files] << {
      title: source[:title],
      source: source[:s3_key].presence || safe_url_label(source[:url]),
      input_file: File.basename(input_path),
      normalized_file: File.basename(output_path),
      measured_loudness: measurement&.dig('input_i'),
      measured_true_peak: measurement&.dig('input_tp'),
      measured_loudness_range: measurement&.dig('input_lra'),
      measured_threshold: measurement&.dig('input_thresh'),
      target_offset: measurement&.dig('target_offset')
    }.compact
  end

  def persist_master(master_path)
    object_key = "broadcast_masters/#{playlist.id}/#{SecureRandom.uuid}/#{master_filename}"
    s3_service.upload_file(master_path, object_key)
    previous_master = playlist.rendered_master_audio_file
    master = nil

    ActiveRecord::Base.transaction do
      master = playlist.user.audio_files.create!(
        name: master_filename,
        title: playlist.name,
        artist: playlist.host_name,
        kind: 'full_show',
        visibility: 'private',
        size: File.size(master_path),
        content_type: 'audio/mpeg',
        duration: playlist.duration_seconds,
        s3_key: object_key,
        notes: master_notes
      )
      playlist.update!(
        rendered_master_audio_file: master,
        render_status: 'ready',
        render_error: nil,
        rendered_at: Time.current,
        delivery_manifest: playlist.delivery_manifest.deep_merge('render_quality_report' => finalized_render_report(master_path, object_key))
      )
    end

    cleanup_previous_master(previous_master, master)
    playlist
  rescue StandardError
    s3_service.delete_file(object_key) if object_key.present?
    raise
  end

  def cleanup_previous_master(previous_master, new_master)
    return if previous_master.blank? || previous_master.id == new_master.id

    s3_service.delete_file(previous_master.s3_key) if previous_master.s3_key.present?
    previous_master.destroy!
  rescue StandardError => error
    Rails.logger.error("Old broadcast master cleanup failed for playlist #{playlist.id}: #{error.message}")
  end

  def master_filename
    "#{playlist.name.parameterize}-broadcast-master.mp3"
  end

  def master_comment
    "#{SOURCE_APP_COMMENT}; normalized to #{TARGET_LOUDNESS} LUFS, #{OUTPUT_SAMPLE_RATE.to_i / 1000} kHz stereo, #{OUTPUT_BITRATE} MP3."
  end

  def master_notes
    "#{master_comment} Render quality report stored on playlist #{playlist.id}."
  end

  def base_render_report
    {
      input_files: [],
      output_file: nil,
      duration_seconds: playlist.duration_seconds,
      target_loudness: {
        integrated_lufs: TARGET_LOUDNESS,
        true_peak_db: TRUE_PEAK,
        loudness_range: LOUDNESS_RANGE
      },
      normalization_mode: 'pending',
      clipping_warnings: [],
      ffmpeg_errors: [],
      metadata_tags: metadata_tags,
      source_app: SOURCE_APP_COMMENT,
      rendered_at: nil
    }
  end

  def finalized_render_report(master_path, object_key)
    render_report.merge(
      output_file: {
        name: master_filename,
        s3_key: object_key,
        size: File.size(master_path),
        content_type: 'audio/mpeg'
      },
      duration_seconds: playlist.duration_seconds,
      rendered_at: Time.current.iso8601
    ).deep_stringify_keys
  end

  def record_failed_report(message)
    report = render_report.merge(
      normalization_mode: render_report[:normalization_mode] == 'pending' ? 'pending' : render_report[:normalization_mode],
      ffmpeg_errors: render_report[:ffmpeg_errors] + [{ message: message }],
      rendered_at: Time.current.iso8601
    ).deep_stringify_keys
    playlist.update_columns(delivery_manifest: playlist.delivery_manifest.deep_merge('render_quality_report' => report)) if playlist.persisted?
  rescue StandardError => error
    Rails.logger.error("Render quality report persistence failed for playlist #{playlist.id}: #{error.message}")
  end

  def metadata_tags
    {
      title: playlist.name,
      artist: playlist.host_name,
      album: playlist.name,
      date: Time.current.year.to_s,
      comment: master_comment
    }
  end

  def safe_url_label(url)
    return if url.blank?

    uri = URI.parse(url)
    "#{uri.scheme}://#{uri.host}#{uri.path}"
  rescue URI::InvalidURIError
    '[invalid-url]'
  end

  def render_report
    @render_report
  end
end
